### ISSUE TITLE
tabouret meditation

### ISSUE THREAD

**Issue by nicolasdb** [nicolasdb/nicolasdb.github.io#106]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*

En 1991, mon bro a fabriqué une série de petit tabouret de méditation. 
Il est praticien en Shiatsu et s'est toujours soucié du bien être des participants à ses cours et pratiques. 
j'en ai encore un que voici:

![image](https://user-images.githubusercontent.com/12049360/46257966-3e701600-c4c3-11e8-90d4-678779e4b26a.png)
![image](https://user-images.githubusercontent.com/12049360/46257973-63fd1f80-c4c3-11e8-9263-061cc62f3788.png)

Modèle rudimentaire, en MP 18mm, vissé, collé et agrafé. Un peu de mousse pour le confort. Done.

En 2014, après ouverture de mon fablab, je possède alors une CNC. Parallèlement, je suis aussi des cours de shiatsu et décide de faire ma version. 

![2014-02-01 20 49 52](https://user-images.githubusercontent.com/12049360/46258063-bee34680-c4c4-11e8-8122-565e635b3264.jpg)
![2014-02-03 11 29 24](https://user-images.githubusercontent.com/12049360/46258064-cb679f00-c4c4-11e8-9ecf-c2f9f2c108bd.jpg)

Le modèle est prototypé en OSB (pas cher, c'est des chutes), optimisé pour un assemblage et désassemblage aisé, pourquoi pas le mettre dans un sachet en coton pour le transport. 
Petite nouveauté, un pied arrondi d'un côté, pour ajuster un peu l'angle de l'assise en fonction de sa physionomie. #tousDifferents 
Le choix peut-être aussi fait sur la hauteur, en changeant les pieds. Pour les plus petits comme pour les plus grands. 

## objectif
2018, je retrouve mon bro dans sa campagne française. 
Il a découvert un fablab dans la région et il aimerait reprendre mon idée d'arrondi et le pousser plus loin encore. _Parce qu'il a plus d'expérience que moi et que l'arrondi au bas des pieds était un peu naif de ma part._ 

Il va repartir de chute aussi. Du chêne, les restes d'un plancher en lattes de 130x23mm. _Un menuisier du coin peux le fournir facilement._ 

## proposition
Il a fait un proto à la main (sorry, pas de photo)
On en est repartis pour un design commun, à usiner en partie sur la cnc du fablab régionnal (sorry, j'ai oublié le nom... )

![image](https://user-images.githubusercontent.com/12049360/46258348-6498b480-c4c9-11e8-9fc0-0d79eb3241c0.png)

Ici, la rotation se fait maintenant au niveau de l'assise, inspiré du col du fémur qui le surplombe, l'articulation est légère, de quelque degré seulement, mais accompagne le bassin lors de la respiration. 
3 hauteurs d'assises est à prévoir pour les différentes tailles.

**Comment by nicolasdb** [comment]
Recherches pour la gravure dessus: 

![image](https://user-images.githubusercontent.com/12049360/46258427-e2a98b00-c4ca-11e8-8dbf-81833a170526.png)

![image](https://www.france-mineraux.fr/wp-content/uploads/2016/09/pierres-mineraux-chakra-racine-muladhara.png)

![image](https://user-images.githubusercontent.com/12049360/46258438-0a98ee80-c4cb-11e8-88ad-305bd183ff00.png)

![image](https://user-images.githubusercontent.com/12049360/46258456-4f248a00-c4cb-11e8-8fe2-f68071c3803d.png)

![chacka](https://cdn.shopify.com/s/files/1/0755/2705/files/icon-chakra-racine.png)

![cgds](https://image.spreadshirtmedia.net/image-server/v1/mp/designs/143162662,width=178,height=178/fleur-de-vie-rouge-chakra-racine.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/46258481-c35f2d80-c4cb-11e8-9c68-acdc0f286f01.png)

**Comment by nicolasdb** [comment]
chakra + cymatics

![image](https://user-images.githubusercontent.com/12049360/46258494-0d481380-c4cc-11e8-9eaa-2dab704586d3.png)

**Comment by nicolasdb** [comment]
Root chakra mandala 

![image](https://user-images.githubusercontent.com/12049360/46258562-4765e500-c4cd-11e8-900d-254bfd92f810.png)
![image](https://user-images.githubusercontent.com/12049360/46258570-62d0f000-c4cd-11e8-8653-7a13da199394.png)

**Comment by nicolasdb** [comment]
first design
![image](https://user-images.githubusercontent.com/12049360/46259576-6cf9eb00-c4db-11e8-9a21-4faa66a52f58.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/46259872-df1fff00-c4de-11e8-8e19-2a07ed5f282a.png)

**Comment by nicolasdb** [comment]
Bien recentrer l'axe en fonction de la colonne vertébrale. 
![image](https://user-images.githubusercontent.com/12049360/71472467-74d63700-27d3-11ea-92a2-71242b5acf80.png)

Inspiration du dolmen, proposition de nom **dolmini**
![image](https://user-images.githubusercontent.com/12049360/71472437-56703b80-27d3-11ea-92a6-ea1d57d73d03.png)
![image](https://user-images.githubusercontent.com/12049360/71472458-6ab43880-27d3-11ea-864d-cb3b3e831536.png)
https://www.fredzone.org/israel-un-mysterieux-dolmen-a-ete-retrouve-en-galilee-554

**Comment by nicolasdb** [comment]
Roulement à billes en verre 
![image](https://user-images.githubusercontent.com/12049360/71473629-0e074c80-27d8-11ea-8306-9996f94f3767.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/71523066-9b759a00-28c7-11ea-97ed-cdf7631d00c6.png)

https://www.intechopen.com/books/machine-learning-and-biometrics/a-human-body-mathematical-model-biometric-using-golden-ratio-a-new-algorithm

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/104348358-f180a400-5501-11eb-93b9-3bc34c1cd5f7.png)

Découpe, test calib etc... 37,5min ~ 9crrr

![image](https://user-images.githubusercontent.com/12049360/104348714-589e5880-5502-11eb-8bc1-2edacd48226b.png)

**Comment by nicolasdb** [comment]
Resultat 15 Janvier: 
- Le point de rotation bas ne fonctionne pas, le mouvement du bassin est très léger, il faut un point de rotation le plus haut possible.  
![image](https://user-images.githubusercontent.com/12049360/104736616-86261480-5743-11eb-935b-62d9b146d0af.png)
Attention au tolérance, la CNC 3040 est nul pour la précision. 
![image](https://user-images.githubusercontent.com/12049360/104736817-c9808300-5743-11eb-9d9a-adaaf06926c4.png)

- La planche du bas, tel quelle est, est difficile à visser et le tabouret est branlant. 
un assemblage à emboitement conviendra mieux pour l'alignement et la finition. 
![image](https://user-images.githubusercontent.com/12049360/104736699-a2c24c80-5743-11eb-8fb2-9e1a33de69c2.png)
L'assemblage est plus rigide et il est possible (a tester) de se passer du renfort. 
- La hauteur est un poil trop basse pour moi, je remonte de 15mm. 
Mais la sensation est bonne. 
L'assise de test pourrait être plus large et plus longue à l'arrière, raccourcie à l'avant pour soulager les cuisses.

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/104745864-d3f44a00-574e-11eb-8cf6-0cc80721d618.png)

**Comment by nicolasdb** [comment]
Achat roulement metal : 
https://shop.jvl-europe.com

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/104748915-82e65500-5752-11eb-94ee-461e96522f84.png)

**Comment by nicolasdb** [comment]
Bon, ensuite je me questionne aussi sur la localisation du tabouret lorsqu'on s'assied. Quand on n'a pas l'habitude, il ne sera probablement pas naturel de s'asseoir au meilleur endroit, du premier coup, bien centré au-dessus de l'axe. 
Je chipote peut-être trop mais je me dis que ça serait pas mal d'avoir un repère de positionnement.

![image](https://user-images.githubusercontent.com/12049360/104755674-0d32b700-575b-11eb-8ce8-d2f350422079.png)

On pourrait avoir une encoche ou simplement faire commencer le pied du tabouret pour qu'il se calle sur le coussinets adipeux, à la base du gros orteil. 
Mais est-ce qu'on peut compter que les proportions humaines restent suffisamment justes pour ça? à quel point c'est important aussi?
 
![image](https://user-images.githubusercontent.com/12049360/104755767-2b98b280-575b-11eb-8f18-9a83c71464d4.png)

**Comment by nicolasdb** [comment]
test gravure laser


![image](https://user-images.githubusercontent.com/12049360/105632364-0428a080-5e53-11eb-980d-daabe713c0f4.png)


fill>contour : jaune > rose , F2000:8 , F1000:10

**Comment by nicolasdb** [comment]
~ 0.6 U laser pour une gravure crosshatch finale. 

![image](https://user-images.githubusercontent.com/12049360/105633882-77ceab80-5e5b-11eb-9bc2-c5f1d119f0a2.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/105741063-2c3eff00-5f3a-11eb-9199-0a8899b0df7f.png)


![image](https://user-images.githubusercontent.com/12049360/105741050-2812e180-5f3a-11eb-9a33-510f78db6218.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/106158581-2fc5c680-6184-11eb-82e0-9ef070f89598.png)

![image](https://user-images.githubusercontent.com/12049360/106158601-35bba780-6184-11eb-9c90-c29df2504e1a.png)

**Comment by nicolasdb** [comment]
Nouvelle gravure laser , 36crrr

**Comment by nicolasdb** [comment]
New charkra
F2000:5 + F1000:12

0.6U = 36 crrr
Plus conso semaine... 4maes, 3 specials = 10 crrr
Total = 46 crrr

![image](https://user-images.githubusercontent.com/12049360/108212818-9fe5bd80-712e-11eb-8ac7-98962a3f7af7.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/109640383-b5a4ab00-7b50-11eb-89c9-7ebe64a8755a.png)

**Comment by nicolasdb** [comment]
### Pourquoi l'inox est-il durable et sain ?
L'inox, cet acier inoxydable, qui a longtemps fait ses preuves. Utilisé aussi bien en intérieur qu'en extérieur, l'inox est connu pour ses propriétés anticorrosives et pour ses qualités de résistance. Si l'inox est reconnu pour sa durabilité, c'est bien car il est capable de tenir plusieurs dizaines d'années sans se détériorer. Cet acier est léger et non toxique, ce qui explique pourquoi il est tant utilisé en cuisine et ustensiles, il n'y a aucun risque de transfert avec les aliments. L'inox est donc un matériau sain. De plus, il est très facile d'entretien. Il est composé de Nickel, de Chrome et d'une très faible quantité de Carbone. Qu'il s'agisse d'inox A2 ou d'inox A4, la particularité de cet acier est avant tout de résister à la rouille en toute circonstance.
https://inoxkit.fr/blog/83/comment-choisir-inox-A2-et-A4.html

**Comment by nicolasdb** [comment]
https://www.aliexpress.com/item/4001273103375.html
![image](https://user-images.githubusercontent.com/12049360/110106011-6a390980-7da9-11eb-9751-70a538a52146.png)

Donc, en quincaillerie: 
- 2x s605zz = 2€
- 2x M5x16 + rondelle= 0.1€

Plus le vernis

Plus le bois:
![image](https://user-images.githubusercontent.com/12049360/110107911-cdc43680-7dab-11eb-94a0-93f99abc5e6f.png)
10€/m² htva chez Carlierbois
1m² = 5 pièces. 
2€ de bois.

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/110131916-f1e34000-7dca-11eb-9da8-0a65ffccc862.png)
150$, naturel, sans gravure
https://www.simplysitting.com/design
#thismachinekillsegos #meditationseat #meditationbench #meditateeveryday #meditationtool #meditationgear #meditateonthis #centering #findtruecenter

---

![image](https://user-images.githubusercontent.com/12049360/110132418-6f0eb500-7dcb-11eb-808c-e24d37a3f176.png)
200€, naturel, sans gravure
https://www.studiovanderzee.com/shop
#smileseat #meditationseat #meditation #mindfulness #finefurniture #finefurnituredesign #peacefulmeditation #madeintirol #madeinaustria #studiovanderzee #mindfulnesspractice #mindfulnessmeditation #headspace #simplysitting #finefurniture #sustainabledesign #furnituredesign #sustainableliving #ergonomics

note: je kif l'idée du foin comme antichoc
![image](https://user-images.githubusercontent.com/12049360/110132695-bd23b880-7dcb-11eb-97be-bfde22c3d584.png)

---

![image](https://user-images.githubusercontent.com/12049360/110132202-366edb80-7dcb-11eb-9ebd-c32d9cddcfd4.png)
https://www.theblissbench.com/shop
#yyj #yyjbusiness #yakisugi #japanesecarpentry #meditationbench #meditationbenches #meditationseat #meditationtools #blissbench #yyjyoga #zenbuddhism #yogacanada

**Comment by nicolasdb** [comment]
### Todo: 

- [ ] photo kit 1, éléments DIY brut. 51€
- [ ] photo modèle classic, sans gravure. 123€
- [ ] photo modèle sérigraphié, 153€
- [ ] photo modèle gravé Epoxy, 244€

**Comment by nicolasdb** [comment]
Thème jekyll site static:

![image](https://user-images.githubusercontent.com/12049360/110134913-33c1b580-7dce-11eb-88cc-2640a3e9e244.png)
http://artemsheludko.com/galada/
J'aime bien le fond taupe, c'est apaisant.

**Comment by nicolasdb** [comment]
#Yogastool 
#meditationstool
#meditationbench
#ecodesign
#ecoconception
#meditation
#maker
#belgianmaker
#handmade
#practicemeditation
#bancdemeditation
#flexibility #flexibilité
#bienetre
#tabouret
#zen
#connection
#unification
#chakra
#spiritualite #spirituality
#conscience
#energie
#eveil
#developpementpersonnel
#introspection

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/112747012-f4444e80-8fb2-11eb-8437-80cf185e88a5.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/112748562-acc2c000-8fbc-11eb-97cf-c8e530570dde.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/112749966-05e32180-8fc6-11eb-9f97-f3fc723607c4.png)
![image](https://user-images.githubusercontent.com/12049360/112749970-0d0a2f80-8fc6-11eb-9924-a63c3865c1e2.png)
![image](https://user-images.githubusercontent.com/12049360/112749972-11364d00-8fc6-11eb-8ff9-0cf4fe4e5464.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/112753423-e5bc5e00-8fd7-11eb-9df9-c7498e65e2d4.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/112753536-26b47280-8fd8-11eb-8c24-f7d5d722ad94.png)
https://sam-ergonomie.fr/salli-concept
![image](https://user-images.githubusercontent.com/12049360/112753596-64b19680-8fd8-11eb-8323-5ff7ee95c749.png)
https://mad4yoga.com/los-conceptos-de-anteversion-y-retroversion-de-la-pelvis/


https://www.yoga-horizon.fr/dans-ton-corps-est-le-mont-meru-shiva-samitha/

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/112754039-9e839c80-8fda-11eb-9785-f6ecef04b16b.png)
https://orthochiro.ca/

**Comment by nicolasdb** [comment]
https://bunq.me/metabouret

les coûts à la pièce, mais produit par série de 10 : 

Offre 1 en kit brut : 
- le bois MP sapin 12mm et cheville de bambou = 4€
- la quincaillerie: 2 roulements + 2 vis = 4€
- découpe cnc 30min = 30€
- R&D design général = + 40% (= 15€)
Total kit: 38 * 1.4 = 53.2€ htva (64.4€ tvac)
Proposé en exclusivité à 59€ tvac, dont 30% sera reversé à Openfab. (= 17.7€)

Offre 2 finit bois naturel: 
- kit = 38€
- colle et vernis = 2€
- 1h Encollage, ponçage, vernissage, taraudage et assemblage = 60€
- R&D design + optimisation de production en petite série = +40% (= 40€)
Total naturel : 100 * 1.4 = 140€ htva (169.4€ tvac)
Proposé en exclusivité à 149€ tvac, dont 30% sera reversé à OF (= 44.7€)

Offre 3 Deluxe:
- la version nature = 100€
- résine epoxy et colorant = 6.5€
- gravure laser 36min = 36€
- bouchepore, epoxy, ponçage et vernis 1h = 60€
- R&D design, optimisation prod, motif et gravure à l'époxy = +40% (= 80.6€)
Total Deluxe : 201.5 * 1.40 = 283.5€ htva (343€ tvac)
Proposé en exclusivité à 300€ tvac, dont 30% sera reversé à OF (= 90€)

**Comment by nicolasdb** [comment]
Autrement dit: 


&nbsp; | Matière première | Machines | Main d'oeuvre | R&amp;D (40%) | Total htva | Total tvac | Today
-- | -- | -- | -- | -- | -- | -- | --
**Kit** | 8,00 € | 30,00 € | 0,00 € | 15,20 € | 53,20 € | ~~64,40 €~~ | **59,00 €**
**Naturel** | 10,00 € | 30,00 € | 60,00 € | 40,00 € | 140,00 € | ~~169,40 €~~ | **149,00 €**
**Deluxe** | 16,50 € | 64,00 € | 120,00 € | 80,20 € | 280,70 € | ~~339,70 €~~ | **300,00 €**

**Comment by nicolasdb** [comment]
## Ce tabouret est un catalyseur d'Eveil. 
Instrumental pour l'Eveil spirituel en aidant la mobilité mécanique du bassin 

![image](https://user-images.githubusercontent.com/12049360/112754122-03d78d80-8fdb-11eb-955b-f73c214d5f8a.png)

Qui permet le relachement des articulations vertébrales et la libre circulation de l'énergie dans les chakra. 

![image](https://user-images.githubusercontent.com/12049360/112753423-e5bc5e00-8fd7-11eb-9df9-c7498e65e2d4.png)


Mais aussi d'Eveil économique, spécifiquement sur le coût réel de fabrication d'un objet.

Notez comme le coût en matière première et en temps machine n'évolue que très peu en fonction du modèle proposé, contrairement au temps de main d'oeuvre et à l'expertise nécessaire pour obtenir le résultat final.  

![image](https://user-images.githubusercontent.com/12049360/120997237-51b10480-c787-11eb-80fc-2c1abe6f299d.png)


Voici l'origine des tarifs proposés:
&nbsp; | Matières | Machines | Main | R&D (40%) | Total htva | Total tvac | Today| 30% pour asbl
-- | -- | -- | -- | -- | -- | -- | --| --
**Kit** | 8,0 € | 30,0 € | 0,0 € | 15,2 € | 53,2 € | ~~64,4 €~~ | **59,0 €** | 17,7 €
**Naturel** | 10,0 € | 30,0 € | 60,0 € | 40,0 € | 140,0 € | ~~169,40€~~ | **149,0 €** | 44,7 €
**Deluxe** | 16,5 € | 64,0 € | 120,0 € | 80,2 € | 280,7 € | ~~339,7 €~~ | **300,0 €** | 90,0 €


## invitation à la mise en perspective:
- Le faire vous même en achetant le kit vous permet d'économiser jusqu'à un montant de 241€, (241€ de **mon temps**)
Les compétences requises sont à portée de tous: coller, poncer et peindre, mais quelle valeur donnez vous à votre temps, et combien allez vous en dépenser? 

- Un tabouret de cuisine Ikea en Pin massif s'achète 12,99€ tvac, essayez de faire l’exercice inverse, qu'est-ce qu'on peut en conclure?
note: en plus de la matière première et du travail en usine, n'oubliez pas le transport, la mise en magasin et les 21% de tva.

**Comment by nicolasdb** [comment]
Tabouret ~~biodynamique~~ magique pour la méditation.
par Nicolas et Thierry de Barquin
version et batch (LOT n°)

Instrumental pour l'Eveil spirituel, en maintenant la mobilité mécanique du bassin....

Fabriqué à Ixelles
Conseils d'utilisation:

**Comment by nicolasdb** [comment]
##version BTC
un peu plus profond. 
2500:12 > passe 1 fill 45° h15
2500:6 > passe 2 fill -45° h15
1000:10 > contour h15
1000:10 > out circle h10

Seulement 0.3U laser > 3x6 = 18crrr
![image](https://user-images.githubusercontent.com/12049360/122643043-bff1b180-d10d-11eb-9008-fd0f78997b50.png)

**Comment by nicolasdb** [comment]
## Production note 011 > 015

- [ ] cut
- [ ] Poncer 80/120
- [ ] Osmo side 1
- [ ] Osmo side 2
- [ ] sign CNC - 4min /pc
- [ ] Engrave laser if needed. + Osmo (bouche-pores)
- [ ] Poncer 180
- [ ] Encoler, 2 sertjoin par pc. Need more. 
- [ ] Forer, cheviller
- [ ] Résine if needed.
